#!/bin/bash

/opt/OV/ServiceActivator/bin/deploymentmanager UndeploySolution -solutionName meracfs  
/opt/OV/ServiceActivator/bin/deploymentmanager DeleteSolution -solutionName meracfs       
/opt/OV/ServiceActivator/bin/deploymentmanager ImportSolution -file /home/rob/jenkins/*.zip
/opt/OV/ServiceActivator/bin/deploymentmanager DeploySolution -solutionName meracfs      

systemctl restart activator.service                 